# Generated by Django 4.0.1 on 2022-01-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('item', models.IntegerField()),
                ('qty', models.FloatField(default=0)),
                ('action', models.CharField(choices=[('shipping', 'Shipping'), ('receiving', 'Receiving'), ('sale_item', 'Sale Item'), ('transfer_item', 'Transfer Item')], default='sale_item', max_length=100)),
                ('source_loc', models.CharField(choices=[('default', 'Default')], default='default', max_length=100)),
                ('source_buc', models.CharField(choices=[('default', ' '), ('on_hand', 'On Hand'), ('at_vendor', 'At Vendor'), ('shipped', 'Shipped'), ('sold', 'Sold'), ('pre_sale', 'Pre-Sale')], default='default', max_length=100)),
                ('dest_loc', models.CharField(choices=[('default', 'Default')], default='default', max_length=100)),
                ('dest_buc', models.CharField(choices=[('default', ' '), ('on_hand', 'On Hand'), ('at_vendor', 'At Vendor'), ('shipped', 'Shipped'), ('sold', 'Sold'), ('pre_sale', 'Pre-Sale')], default='default', max_length=100)),
            ],
        ),
    ]
